# ===============================
# APPLICATION
# ===============================

spring.application.name=tourism-management-system


# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/tourism_db
spring.datasource.username=postgres
spring.datasource.password=Sagar


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# SERVER
# ===============================

server.port=8080


# ===============================
# JWT
# ===============================

jwt.secret=ThisIsMyVerySecureSecretKeyForTourismManagementSystem2026
jwt.expiration=86400000


logging.level.org.springframework.security=DEBUG


# ==========================================
# EMAIL CONFIGURATION
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=suyogsagar43@gmail.com
spring.mail.password=ephw sclv icdl bzrd

# ==========================================
# TOURISM EMAIL CONFIGURATION
# ==========================================

tourism.email.cc=sagarsharmarabi@gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# WhatsApp API (Twilio) Settings
twilio.account.sid=AC_dummy_account_sid
twilio.auth.token=dummy_auth_token
twilio.whatsapp.sender=+9779801046037


# ==========================================
# FILE UPLOAD CONFIGURATION
# ==========================================
file.upload-dir=uploads/documents
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB